# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Japanese Weather MCP Server

# Build stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install
RUN npm run build

# Production stage
FROM node:lts-alpine AS runner
WORKDIR /app

# Install production dependencies only
COPY package.json package-lock.json ./
RUN npm install --omit=dev

# Copy built artifacts
COPY --from=builder /app/dist ./dist

# Default command to run the MCP stdio server
CMD ["node", "dist/server.js"]
